/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Program = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const AcademyData = IDL.Record({
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'programs' : IDL.Vec(Program),
  'contactEmail' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAcademyData' : IDL.Func([], [AcademyData], ['query']),
  'getAllPrograms' : IDL.Func([], [IDL.Vec(Program)], ['query']),
  'getProgramsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Program)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Program = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const AcademyData = IDL.Record({
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'programs' : IDL.Vec(Program),
    'contactEmail' : IDL.Text,
  });
  
  return IDL.Service({
    'getAcademyData' : IDL.Func([], [AcademyData], ['query']),
    'getAllPrograms' : IDL.Func([], [IDL.Vec(Program)], ['query']),
    'getProgramsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Program)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };